on:
  push:
    paths:
      - 'notes/src/notes/**/*.tex'
      - 'notes/src/notes/**'
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra biber latexmk

    - name: Compile all .tex files in notes/src/notes
      run: |
        mkdir -p pdfs
        for texfile in notes/src/notes/*.tex; do
          filename=$(basename "$texfile" .tex)
          echo "Compiling $filename.tex"
          latexmk -pdf -interaction=nonstopmode -outdir=pdfs "$texfile"
        done

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdfs
        path: pdfs/*.pdf

