on:
  push:
    branches:
      - master
    paths:
      - 'notes/**'

permissions:
  contents: write

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra texlive-lang-french texlive-pictures texlive-science latexmk

    - name: Compile all .tex files in notes/src/notes
      run: |
        mkdir -p pdfs
        cd notes
        for texfile in src/notes/*.tex; do
          filename=$(basename "$texfile" .tex)
          echo "Compiling $filename.tex"
          latexmk -pdf -interaction=nonstopmode -outdir=pdfs "$texfile"
        done

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: notes/pdfs/*.pdf

    - name: Create HTML index for PDFs
      run: |
        cd notes/pdfs
        echo "<!DOCTYPE html>
        <html>
        <head>
          <meta charset='UTF-8'>
          <title>My Machine Learning Notes</title>
        </head>
        <body>
          <h1>PDF Notes</h1>
          <ul>" > index.html

                for pdf in *.pdf; do
                  echo "<li><a href=\"$pdf\">$pdf</a></li>" >> index.html
                done

                echo "</ul>
        </body>
        </html>" >> index.html


    - name: Deploy PDFs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./notes/pdfs
        publish_branch: gh-pages
        force_orphan: true
